// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/tool/grpctool/grpctool.proto

package grpctool

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on HttpRequest with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *HttpRequest) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Message.(type) {

	case *HttpRequest_Header_:

		if v, ok := interface{}(m.GetHeader()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpRequestValidationError{
					field:  "Header",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *HttpRequest_Data_:

		if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpRequestValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *HttpRequest_Trailer_:

		if v, ok := interface{}(m.GetTrailer()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpRequestValidationError{
					field:  "Trailer",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		return HttpRequestValidationError{
			field:  "Message",
			reason: "value is required",
		}

	}

	return nil
}

// HttpRequestValidationError is the validation error returned by
// HttpRequest.Validate if the designated constraints aren't met.
type HttpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpRequestValidationError) ErrorName() string { return "HttpRequestValidationError" }

// Error satisfies the builtin error interface
func (e HttpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpRequestValidationError{}

// Validate checks the field values on HttpResponse with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *HttpResponse) Validate() error {
	if m == nil {
		return nil
	}

	switch m.Message.(type) {

	case *HttpResponse_Header_:

		if v, ok := interface{}(m.GetHeader()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpResponseValidationError{
					field:  "Header",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *HttpResponse_Data_:

		if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *HttpResponse_Trailer_:

		if v, ok := interface{}(m.GetTrailer()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HttpResponseValidationError{
					field:  "Trailer",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		return HttpResponseValidationError{
			field:  "Message",
			reason: "value is required",
		}

	}

	return nil
}

// HttpResponseValidationError is the validation error returned by
// HttpResponse.Validate if the designated constraints aren't met.
type HttpResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpResponseValidationError) ErrorName() string { return "HttpResponseValidationError" }

// Error satisfies the builtin error interface
func (e HttpResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpResponseValidationError{}

// Validate checks the field values on HttpRequest_Header with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *HttpRequest_Header) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetRequest() == nil {
		return HttpRequest_HeaderValidationError{
			field:  "Request",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetRequest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpRequest_HeaderValidationError{
				field:  "Request",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetExtra()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpRequest_HeaderValidationError{
				field:  "Extra",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// HttpRequest_HeaderValidationError is the validation error returned by
// HttpRequest_Header.Validate if the designated constraints aren't met.
type HttpRequest_HeaderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpRequest_HeaderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpRequest_HeaderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpRequest_HeaderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpRequest_HeaderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpRequest_HeaderValidationError) ErrorName() string {
	return "HttpRequest_HeaderValidationError"
}

// Error satisfies the builtin error interface
func (e HttpRequest_HeaderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpRequest_Header.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpRequest_HeaderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpRequest_HeaderValidationError{}

// Validate checks the field values on HttpRequest_Data with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *HttpRequest_Data) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Data

	return nil
}

// HttpRequest_DataValidationError is the validation error returned by
// HttpRequest_Data.Validate if the designated constraints aren't met.
type HttpRequest_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpRequest_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpRequest_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpRequest_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpRequest_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpRequest_DataValidationError) ErrorName() string { return "HttpRequest_DataValidationError" }

// Error satisfies the builtin error interface
func (e HttpRequest_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpRequest_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpRequest_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpRequest_DataValidationError{}

// Validate checks the field values on HttpRequest_Trailer with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *HttpRequest_Trailer) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// HttpRequest_TrailerValidationError is the validation error returned by
// HttpRequest_Trailer.Validate if the designated constraints aren't met.
type HttpRequest_TrailerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpRequest_TrailerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpRequest_TrailerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpRequest_TrailerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpRequest_TrailerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpRequest_TrailerValidationError) ErrorName() string {
	return "HttpRequest_TrailerValidationError"
}

// Error satisfies the builtin error interface
func (e HttpRequest_TrailerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpRequest_Trailer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpRequest_TrailerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpRequest_TrailerValidationError{}

// Validate checks the field values on HttpResponse_Header with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *HttpResponse_Header) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetResponse() == nil {
		return HttpResponse_HeaderValidationError{
			field:  "Response",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetResponse()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return HttpResponse_HeaderValidationError{
				field:  "Response",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// HttpResponse_HeaderValidationError is the validation error returned by
// HttpResponse_Header.Validate if the designated constraints aren't met.
type HttpResponse_HeaderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpResponse_HeaderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpResponse_HeaderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpResponse_HeaderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpResponse_HeaderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpResponse_HeaderValidationError) ErrorName() string {
	return "HttpResponse_HeaderValidationError"
}

// Error satisfies the builtin error interface
func (e HttpResponse_HeaderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpResponse_Header.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpResponse_HeaderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpResponse_HeaderValidationError{}

// Validate checks the field values on HttpResponse_Data with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *HttpResponse_Data) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Data

	return nil
}

// HttpResponse_DataValidationError is the validation error returned by
// HttpResponse_Data.Validate if the designated constraints aren't met.
type HttpResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpResponse_DataValidationError) ErrorName() string {
	return "HttpResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e HttpResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpResponse_DataValidationError{}

// Validate checks the field values on HttpResponse_Trailer with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *HttpResponse_Trailer) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// HttpResponse_TrailerValidationError is the validation error returned by
// HttpResponse_Trailer.Validate if the designated constraints aren't met.
type HttpResponse_TrailerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HttpResponse_TrailerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HttpResponse_TrailerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HttpResponse_TrailerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HttpResponse_TrailerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HttpResponse_TrailerValidationError) ErrorName() string {
	return "HttpResponse_TrailerValidationError"
}

// Error satisfies the builtin error interface
func (e HttpResponse_TrailerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHttpResponse_Trailer.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HttpResponse_TrailerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HttpResponse_TrailerValidationError{}
