// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agentrpc/agentrpc.proto

package agentrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KubernetesRequestMeta struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KubernetesRequestMeta) Reset()         { *m = KubernetesRequestMeta{} }
func (m *KubernetesRequestMeta) String() string { return proto.CompactTextString(m) }
func (*KubernetesRequestMeta) ProtoMessage()    {}
func (*KubernetesRequestMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_53eb4ed12d68dab5, []int{0}
}

func (m *KubernetesRequestMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesRequestMeta.Unmarshal(m, b)
}
func (m *KubernetesRequestMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesRequestMeta.Marshal(b, m, deterministic)
}
func (m *KubernetesRequestMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesRequestMeta.Merge(m, src)
}
func (m *KubernetesRequestMeta) XXX_Size() int {
	return xxx_messageInfo_KubernetesRequestMeta.Size(m)
}
func (m *KubernetesRequestMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesRequestMeta.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesRequestMeta proto.InternalMessageInfo

func (m *KubernetesRequestMeta) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type HttpHeader struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []string `protobuf:"bytes,2,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HttpHeader) Reset()         { *m = HttpHeader{} }
func (m *HttpHeader) String() string { return proto.CompactTextString(m) }
func (*HttpHeader) ProtoMessage()    {}
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_53eb4ed12d68dab5, []int{1}
}

func (m *HttpHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpHeader.Unmarshal(m, b)
}
func (m *HttpHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpHeader.Marshal(b, m, deterministic)
}
func (m *HttpHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpHeader.Merge(m, src)
}
func (m *HttpHeader) XXX_Size() int {
	return xxx_messageInfo_HttpHeader.Size(m)
}
func (m *HttpHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpHeader.DiscardUnknown(m)
}

var xxx_messageInfo_HttpHeader proto.InternalMessageInfo

func (m *HttpHeader) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HttpHeader) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type KubernetesRequest struct {
	Meta                 *KubernetesRequestMeta `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Method               string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	UriPathAndQuery      string                 `protobuf:"bytes,3,opt,name=uri_path_and_query,json=uriPathAndQuery,proto3" json:"uri_path_and_query,omitempty"`
	Headers              []*HttpHeader          `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *KubernetesRequest) Reset()         { *m = KubernetesRequest{} }
func (m *KubernetesRequest) String() string { return proto.CompactTextString(m) }
func (*KubernetesRequest) ProtoMessage()    {}
func (*KubernetesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_53eb4ed12d68dab5, []int{2}
}

func (m *KubernetesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesRequest.Unmarshal(m, b)
}
func (m *KubernetesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesRequest.Marshal(b, m, deterministic)
}
func (m *KubernetesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesRequest.Merge(m, src)
}
func (m *KubernetesRequest) XXX_Size() int {
	return xxx_messageInfo_KubernetesRequest.Size(m)
}
func (m *KubernetesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesRequest proto.InternalMessageInfo

func (m *KubernetesRequest) GetMeta() *KubernetesRequestMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *KubernetesRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *KubernetesRequest) GetUriPathAndQuery() string {
	if m != nil {
		return m.UriPathAndQuery
	}
	return ""
}

func (m *KubernetesRequest) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *KubernetesRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type KubernetesResponse struct {
	StatusCode           uint32        `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage        string        `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Headers              []*HttpHeader `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body                 []byte        `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *KubernetesResponse) Reset()         { *m = KubernetesResponse{} }
func (m *KubernetesResponse) String() string { return proto.CompactTextString(m) }
func (*KubernetesResponse) ProtoMessage()    {}
func (*KubernetesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_53eb4ed12d68dab5, []int{3}
}

func (m *KubernetesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KubernetesResponse.Unmarshal(m, b)
}
func (m *KubernetesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KubernetesResponse.Marshal(b, m, deterministic)
}
func (m *KubernetesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KubernetesResponse.Merge(m, src)
}
func (m *KubernetesResponse) XXX_Size() int {
	return xxx_messageInfo_KubernetesResponse.Size(m)
}
func (m *KubernetesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KubernetesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KubernetesResponse proto.InternalMessageInfo

func (m *KubernetesResponse) GetStatusCode() uint32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *KubernetesResponse) GetStatusMessage() string {
	if m != nil {
		return m.StatusMessage
	}
	return ""
}

func (m *KubernetesResponse) GetHeaders() []*HttpHeader {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *KubernetesResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*KubernetesRequestMeta)(nil), "agentrpc.KubernetesRequestMeta")
	proto.RegisterType((*HttpHeader)(nil), "agentrpc.HttpHeader")
	proto.RegisterType((*KubernetesRequest)(nil), "agentrpc.KubernetesRequest")
	proto.RegisterType((*KubernetesResponse)(nil), "agentrpc.KubernetesResponse")
}

func init() { proto.RegisterFile("agentrpc/agentrpc.proto", fileDescriptor_53eb4ed12d68dab5) }

var fileDescriptor_53eb4ed12d68dab5 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdd, 0xea, 0xd3, 0x40,
	0x10, 0xc5, 0x4d, 0x93, 0x56, 0x3b, 0xb1, 0x7e, 0x8c, 0x55, 0x83, 0x1f, 0x34, 0x04, 0x84, 0x80,
	0x50, 0xa5, 0x15, 0xef, 0xc5, 0x0b, 0x2b, 0x52, 0xa9, 0xeb, 0x03, 0x84, 0x6d, 0x76, 0x68, 0x82,
	0x6d, 0x36, 0xdd, 0x8f, 0x62, 0xde, 0xc6, 0x57, 0xf2, 0x8d, 0xa4, 0x9b, 0xd4, 0x16, 0x2c, 0xc2,
	0xff, 0x6e, 0xe6, 0x70, 0xc2, 0xf9, 0x9d, 0xc9, 0xc2, 0x53, 0xbe, 0xa1, 0xca, 0xa8, 0x3a, 0x7f,
	0x73, 0x1a, 0xa6, 0xb5, 0x92, 0x46, 0xe2, 0x9d, 0xd3, 0x9e, 0xbc, 0x87, 0xc7, 0x5f, 0xec, 0x9a,
	0x54, 0x45, 0x86, 0x34, 0xa3, 0xbd, 0x25, 0x6d, 0x96, 0x64, 0x38, 0xbe, 0x04, 0xc8, 0xb7, 0x56,
	0x1b, 0x52, 0x59, 0x29, 0x22, 0x2f, 0xf6, 0xd2, 0x21, 0x1b, 0x76, 0xca, 0x67, 0x91, 0xbc, 0x03,
	0x58, 0x18, 0x53, 0x2f, 0x88, 0x0b, 0x52, 0xf8, 0x00, 0xfc, 0x1f, 0xd4, 0x74, 0xae, 0xe3, 0x88,
	0x63, 0xe8, 0x1f, 0xf8, 0xd6, 0x52, 0xd4, 0x8b, 0xfd, 0x74, 0xc8, 0xda, 0x25, 0xf9, 0xed, 0xc1,
	0xc3, 0x7f, 0xe2, 0x70, 0x0e, 0xc1, 0x8e, 0x0c, 0x77, 0x9f, 0x87, 0xb3, 0xc9, 0xf4, 0x2f, 0xec,
	0x55, 0x32, 0xe6, 0xcc, 0xf8, 0x04, 0x06, 0x3b, 0x32, 0x85, 0x14, 0x51, 0xcf, 0xa5, 0x76, 0x1b,
	0xbe, 0x06, 0xb4, 0xaa, 0xcc, 0x6a, 0x6e, 0x8a, 0x8c, 0x57, 0x22, 0xdb, 0x5b, 0x52, 0x4d, 0xe4,
	0x3b, 0xcf, 0x7d, 0xab, 0xca, 0x15, 0x37, 0xc5, 0x87, 0x4a, 0x7c, 0x3b, 0xca, 0x38, 0x85, 0xdb,
	0x85, 0x6b, 0xa0, 0xa3, 0x20, 0xf6, 0xd3, 0x70, 0x36, 0x3e, 0x87, 0x9f, 0xeb, 0xb1, 0x93, 0x09,
	0x11, 0x82, 0xb5, 0x14, 0x4d, 0xd4, 0x8f, 0xbd, 0xf4, 0x2e, 0x73, 0x73, 0xf2, 0xcb, 0x03, 0xbc,
	0x04, 0xd5, 0xb5, 0xac, 0x34, 0xe1, 0x04, 0x42, 0x6d, 0xb8, 0xb1, 0x3a, 0xcb, 0xa5, 0x20, 0xd7,
	0x6d, 0xc4, 0xa0, 0x95, 0x3e, 0x4a, 0x41, 0xf8, 0x0a, 0xee, 0x75, 0x86, 0x1d, 0x69, 0xcd, 0x37,
	0xd4, 0x15, 0x19, 0xb5, 0xea, 0xb2, 0x15, 0x2f, 0x11, 0xfd, 0x9b, 0x20, 0x06, 0x67, 0xc4, 0x19,
	0xc1, 0x23, 0x46, 0x07, 0x52, 0x9a, 0x56, 0x4a, 0xfe, 0x6c, 0xbe, 0x93, 0x3a, 0x94, 0x39, 0xe1,
	0x57, 0x08, 0x3f, 0x91, 0xe9, 0x4e, 0xab, 0xf1, 0xc5, 0xf5, 0xc3, 0xb7, 0x7d, 0x9e, 0x3d, 0xff,
	0xcf, 0x6f, 0x49, 0x6e, 0xa5, 0xde, 0x5b, 0x6f, 0x3d, 0x70, 0x8f, 0x6b, 0xfe, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x0a, 0x0b, 0x3d, 0x41, 0x77, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReverseProxyServiceClient is the client API for ReverseProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReverseProxyServiceClient interface {
	GetRequests(ctx context.Context, opts ...grpc.CallOption) (ReverseProxyService_GetRequestsClient, error)
}

type reverseProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseProxyServiceClient(cc grpc.ClientConnInterface) ReverseProxyServiceClient {
	return &reverseProxyServiceClient{cc}
}

func (c *reverseProxyServiceClient) GetRequests(ctx context.Context, opts ...grpc.CallOption) (ReverseProxyService_GetRequestsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ReverseProxyService_serviceDesc.Streams[0], "/agentrpc.ReverseProxyService/GetRequests", opts...)
	if err != nil {
		return nil, err
	}
	x := &reverseProxyServiceGetRequestsClient{stream}
	return x, nil
}

type ReverseProxyService_GetRequestsClient interface {
	Send(*KubernetesResponse) error
	Recv() (*KubernetesRequest, error)
	grpc.ClientStream
}

type reverseProxyServiceGetRequestsClient struct {
	grpc.ClientStream
}

func (x *reverseProxyServiceGetRequestsClient) Send(m *KubernetesResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reverseProxyServiceGetRequestsClient) Recv() (*KubernetesRequest, error) {
	m := new(KubernetesRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReverseProxyServiceServer is the server API for ReverseProxyService service.
type ReverseProxyServiceServer interface {
	GetRequests(ReverseProxyService_GetRequestsServer) error
}

// UnimplementedReverseProxyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReverseProxyServiceServer struct {
}

func (*UnimplementedReverseProxyServiceServer) GetRequests(srv ReverseProxyService_GetRequestsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRequests not implemented")
}

func RegisterReverseProxyServiceServer(s *grpc.Server, srv ReverseProxyServiceServer) {
	s.RegisterService(&_ReverseProxyService_serviceDesc, srv)
}

func _ReverseProxyService_GetRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReverseProxyServiceServer).GetRequests(&reverseProxyServiceGetRequestsServer{stream})
}

type ReverseProxyService_GetRequestsServer interface {
	Send(*KubernetesRequest) error
	Recv() (*KubernetesResponse, error)
	grpc.ServerStream
}

type reverseProxyServiceGetRequestsServer struct {
	grpc.ServerStream
}

func (x *reverseProxyServiceGetRequestsServer) Send(m *KubernetesRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reverseProxyServiceGetRequestsServer) Recv() (*KubernetesResponse, error) {
	m := new(KubernetesResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ReverseProxyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agentrpc.ReverseProxyService",
	HandlerType: (*ReverseProxyServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRequests",
			Handler:       _ReverseProxyService_GetRequests_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentrpc/agentrpc.proto",
}
