# This is a sample configuration file for kas. The source of truth is pkg/kascfg/kascfg.proto. It contains documentation
# for all the fields. Configuration values in this file are the defaults (if set) that are used by kas.

gitlab:
  address: http://localhost:8080 # required
  authentication_secret_file: /some/file # required
  # ca_certificate_file: /server-ca.pem
  api_rate_limit:
    refill_rate_per_second: 10.0
    bucket_size: 50
agent:
  listen:
    network: tcp
    address: 127.0.0.1:8150
    websocket: false
    # certificate_file: /server-cert.pem
    # key_file: /server-key.pem
    connections_per_token_per_minute: 100
    max_connection_age: "1800s"
  configuration:
    poll_period: "20s"
    max_configuration_file_size: 131072
  gitops:
    poll_period: "20s"
    project_info_cache_ttl: "300s"
    project_info_cache_error_ttl: "60s"
    max_manifest_file_size: 1048576
    max_total_manifest_file_size: 2097152
    max_number_of_paths: 100
    max_number_of_files: 1000
  info_cache_ttl: "300s"
  info_cache_error_ttl: "60s"
  redis_conn_info_ttl: "300s"
  redis_conn_info_refresh: "240s"
  redis_conn_info_gc: "600s"
observability:
  usage_reporting_period: "60s"
  listen:
    network: tcp
    address: 0.0.0.0:8151
  prometheus:
    url_path: /metrics
  tracing:
    connection_string: ""
  sentry:
    dsn: ""
    environment: ""
  logging:
    level: info
  google_profiler:
    enabled: false
    # project_id: ""
    # credentials_file: /some/file
  liveness_probe:
    url_path: /liveness
  readiness_probe:
    url_path: /readiness
gitaly:
  global_api_rate_limit:
    refill_rate_per_second: 10.0
    bucket_size: 50
  per_server_api_rate_limit:
    refill_rate_per_second: 5.0
    bucket_size: 10
redis:
  url: unix:///tmp/redis.sock # required if redis block is present
  #  password: my-password
  max_idle: 1
  max_active: 1
  read_timeout: "1s"
  write_timeout: "1s"
  keepalive: "300s"
  #  sentinel_master: my-master
  #  sentinels: [ tcp://host-1, tcp://host-2 ]
  key_prefix: gitlab-kas
