// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/module/configuration_project/rpc/rpc.proto

package rpc

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ListAgentConfigFilesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListAgentConfigFilesRequest) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetRepository() == nil {
		return ListAgentConfigFilesRequestValidationError{
			field:  "Repository",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetRepository()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListAgentConfigFilesRequestValidationError{
				field:  "Repository",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetGitalyAddress() == nil {
		return ListAgentConfigFilesRequestValidationError{
			field:  "GitalyAddress",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetGitalyAddress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListAgentConfigFilesRequestValidationError{
				field:  "GitalyAddress",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ListAgentConfigFilesRequestValidationError is the validation error returned
// by ListAgentConfigFilesRequest.Validate if the designated constraints
// aren't met.
type ListAgentConfigFilesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAgentConfigFilesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAgentConfigFilesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAgentConfigFilesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAgentConfigFilesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAgentConfigFilesRequestValidationError) ErrorName() string {
	return "ListAgentConfigFilesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAgentConfigFilesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAgentConfigFilesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAgentConfigFilesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAgentConfigFilesRequestValidationError{}

// Validate checks the field values on ListAgentConfigFilesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListAgentConfigFilesResponse) Validate() error {
	if m == nil {
		return nil
	}

	for idx, item := range m.GetConfigFiles() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAgentConfigFilesResponseValidationError{
					field:  fmt.Sprintf("ConfigFiles[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListAgentConfigFilesResponseValidationError is the validation error returned
// by ListAgentConfigFilesResponse.Validate if the designated constraints
// aren't met.
type ListAgentConfigFilesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAgentConfigFilesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAgentConfigFilesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAgentConfigFilesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAgentConfigFilesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAgentConfigFilesResponseValidationError) ErrorName() string {
	return "ListAgentConfigFilesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAgentConfigFilesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAgentConfigFilesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAgentConfigFilesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAgentConfigFilesResponseValidationError{}

// Validate checks the field values on AgentConfigFile with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *AgentConfigFile) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	// no validation rules for AgentName

	return nil
}

// AgentConfigFileValidationError is the validation error returned by
// AgentConfigFile.Validate if the designated constraints aren't met.
type AgentConfigFileValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgentConfigFileValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgentConfigFileValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgentConfigFileValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgentConfigFileValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgentConfigFileValidationError) ErrorName() string { return "AgentConfigFileValidationError" }

// Error satisfies the builtin error interface
func (e AgentConfigFileValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgentConfigFile.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgentConfigFileValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgentConfigFileValidationError{}
