# This is a sample configuration file for kas. The source of truth is pkg/kascfg/kascfg.proto. It contains documentation
# for all the fields. Configuration values in this file are the defaults (if set) that are used by kas.

listen:
  network: tcp
  address: 127.0.0.1:8150
  websocket: false
gitlab:
  address: http://localhost:8080
  # authentication_secret_file: /some/file
agent:
  configuration:
    poll_period: "20s"
  gitops:
    poll_period: "20s"
    project_info_cache_ttl: "300s"
    project_info_cache_error_ttl: "60s"
  info_cache_ttl: "300s"
  info_cache_error_ttl: "60s"
observability:
  usage_reporting_period: "60s"
  listen:
    network: tcp
    address: 127.0.0.1:8151
  prometheus:
    disabled: false
    url_path: /metrics
  tracing:
    connection_string: ""
gitaly:
  global_api_rate_limit:
    refill_rate_per_second: 10.0
    bucket_size: 50
