# This is a sample configuration file for kas. The source of truth is pkg/kascfg/kascfg.proto. It contains documentation
# for all the fields. Configuration values in this file are the defaults (if set) that are used by kas.

listen:
  network: tcp
  address: 127.0.0.1:8150
  websocket: false
gitlab:
  address: http://localhost:8080
  # authentication_secret_file: /some/file
agent:
  configuration:
    poll_period: "20s"
  gitops:
    poll_period: "20s"
    project_info_cache_ttl: "300s"
    project_info_cache_error_ttl: "60s"
  info_cache_ttl: "300s"
  info_cache_error_ttl: "60s"
  limits:
    connections_per_token_per_minute: 100
    redis_key_prefix: kas:agent_limits
observability:
  usage_reporting_period: "60s"
  listen:
    network: tcp
    address: 127.0.0.1:8151
  prometheus:
    disabled: false
    url_path: /metrics
  tracing:
    connection_string: ""
  sentry:
    dsn: ""
    environment: ""
gitaly:
  global_api_rate_limit:
    refill_rate_per_second: 10.0
    bucket_size: 50
  per_server_api_rate_limit:
    refill_rate_per_second: 5.0
    bucket_size: 10
# redis:
#   url: unix:///tmp/redis.sock
#   # password: my-password
#   max_idle: 1
#   max_active: 1
#   read_timeout: "1s"
#   write_timeout: "1s"
#   keepalive: "300s"
#   # sentinel_master: my-master
#   # sentinels: [ tcp://host-1, tcp://host-2]
