# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: internal/module/configuration_project/rpc/rpc.proto for package 'gitlab.agent.configuration_project.rpc'

require 'grpc'
require 'internal/module/configuration_project/rpc/rpc_pb'

module Gitlab
  module Agent
    module ConfigurationProject
      module Rpc
        module ConfigurationProject
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'gitlab.agent.configuration_project.rpc.ConfigurationProject'

            rpc :ListAgentConfigFiles, ::Gitlab::Agent::ConfigurationProject::Rpc::ListAgentConfigFilesRequest, ::Gitlab::Agent::ConfigurationProject::Rpc::ListAgentConfigFilesResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
